services:
  - type: web
    name: lelocal-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
    disk:
      enabled: true
      mountPath: /app
      size: 1